# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pinplan.xdc

# Block Designs: bd/xnor_soc/xnor_soc.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xnor_soc || ORIG_REF_NAME==xnor_soc} -quiet] -quiet

# IP: bd/xnor_soc/ip/xnor_soc_processing_system7_0_0/xnor_soc_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xnor_soc_processing_system7_0_0 || ORIG_REF_NAME==xnor_soc_processing_system7_0_0} -quiet] -quiet

# IP: bd/xnor_soc/ip/xnor_soc_axi_gpio_0_0/xnor_soc_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xnor_soc_axi_gpio_0_0 || ORIG_REF_NAME==xnor_soc_axi_gpio_0_0} -quiet] -quiet

# IP: bd/xnor_soc/ip/xnor_soc_xbar_0/xnor_soc_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xnor_soc_xbar_0 || ORIG_REF_NAME==xnor_soc_xbar_0} -quiet] -quiet

# IP: bd/xnor_soc/ip/xnor_soc_ps7_0_axi_periph_0/xnor_soc_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xnor_soc_ps7_0_axi_periph_0 || ORIG_REF_NAME==xnor_soc_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/xnor_soc/ip/xnor_soc_rst_ps7_0_50M_0/xnor_soc_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xnor_soc_rst_ps7_0_50M_0 || ORIG_REF_NAME==xnor_soc_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/xnor_soc/ip/xnor_soc_axi_gpio_1_0/xnor_soc_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xnor_soc_axi_gpio_1_0 || ORIG_REF_NAME==xnor_soc_axi_gpio_1_0} -quiet] -quiet

# IP: bd/xnor_soc/ip/xnor_soc_xnor_hw_0_0/xnor_soc_xnor_hw_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xnor_soc_xnor_hw_0_0 || ORIG_REF_NAME==xnor_soc_xnor_hw_0_0} -quiet] -quiet

# IP: bd/xnor_soc/ip/xnor_soc_auto_pc_0/xnor_soc_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xnor_soc_auto_pc_0 || ORIG_REF_NAME==xnor_soc_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/FDP2024/Desktop/xnor/xnor.gen/sources_1/bd/xnor_soc/xnor_soc_ooc.xdc
