# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/FDP2024/Desktop/xnor/xnor.srcs/sources_1/bd/xnor_soc/ip/xnor_soc_xbar_0/xnor_soc_xbar_0.xci
# IP: The module: 'xnor_soc_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/FDP2024/Desktop/xnor/xnor.gen/sources_1/bd/xnor_soc/ip/xnor_soc_xbar_0/xnor_soc_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xnor_soc_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/FDP2024/Desktop/xnor/xnor.srcs/sources_1/bd/xnor_soc/ip/xnor_soc_xbar_0/xnor_soc_xbar_0.xci
# IP: The module: 'xnor_soc_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/FDP2024/Desktop/xnor/xnor.gen/sources_1/bd/xnor_soc/ip/xnor_soc_xbar_0/xnor_soc_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xnor_soc_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
